image: fommil/dotfiles

script:
  - TESTS=`find . -name "[0-9]*.el" | sed 's|^|--load |' | sort` ;
    $EMACS --batch --no-site-file --no-init-file --load ert --load e99utils.el $TESTS -f ert-run-tests-batch-and-exit

env:
  - EMACS=/opt/emacs-24.5/bin/emacs

